### ISSUE TITLE
Azure Board issue tracker support 

### ISSUE THREAD

**Issue by mateusoliveira43** [dora-metrics/pelorus#915]
### Feature

Users have requested for [Azure Board](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/manage-bugs?view=azure-devops) (Azure devops issue tracker) support by Pelorus.

### Requirements

- [x] Study
  - [x] [Azure Board REST API ](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/get-work-items-batch?view=azure-devops-rest-7.0&tabs=HTTP)
  - [x] Use cases of issues (called work items? labels? filtering?)
- [x] Documentation
  - [x] Add it to supported providers
    - [x] https://pelorus.readthedocs.io/en/latest/UpstreamSupport/
  - [x] Add instructions on how to set it up with Pelorus
- [x]  Tests
  - [x] unit
  - [x] integration
  - [x] end to end
    - [x] Add credentials to Prow
    - [x] mig demo apps PR https://github.com/konveyor/mig-demo-apps/pull/100
